const cart = [
  {
    name: 'Thon',
    category: 'Sandwich',
    unitPrice: 1.5,
    totalPrice: 0,
    quantity: 0,
  },
  {
    name: 'Thon',
    category: 'Sandwich',
    unitPrice: 1.5,
    totalPrice: 0,
    quantity: 0,
  },
  {
    name: 'Thon',
    category: 'Sandwich',
    unitPrice: 1.5,
    totalPrice: 0,
    quantity: 0,
  },
  {
    name: 'Thon',
    category: 'Sandwich',
    unitPrice: 1.5,
    totalPrice: 0,
    quantity: 0,
  },
  {
    name: 'Thon',
    category: 'Sandwich',
    unitPrice: 1.5,
    totalPrice: 0,
    quantity: 0,
  },
  {
    name: 'Thon',
    category: 'Sandwich',
    unitPrice: 1.5,
    totalPrice: 0,
    quantity: 0,
  },
  {
    name: 'Thon',
    category: 'Sandwich',
    unitPrice: 1.5,
    totalPrice: 0,
    quantity: 0,
  },
  {
    name: 'Blé',
    category: 'Sandwich',
    unitPrice: 2,
    totalPrice: 0,
    quantity: 0,
  },
  {
    name: 'Thon',
    category: 'Sandwich',
    unitPrice: 1.5,
    totalPrice: 0,
    quantity: 0,
  },
  {
    name: 'Thé bio',
    category: 'Boisson',
    unitPrice: 1,
    totalPrice: 0,
    quantity: 0,
  },
  {
    name: 'Thé bio',
    category: 'Boisson',
    unitPrice: 1,
    totalPrice: 0,
    quantity: 0,
  },
  {
    name: 'Thé bio',
    category: 'Boisson',
    unitPrice: 1,
    totalPrice: 0,
    quantity: 0,
  },
  {
    name: 'Thé bio',
    category: 'Boisson',
    unitPrice: 1,
    totalPrice: 0,
    quantity: 0,
  },
  {
    name: 'Thé bio',
    category: 'Boisson',
    unitPrice: 1,
    totalPrice: 0,
    quantity: 0,
  },
  {
    name: 'Thé bio',
    category: 'Boisson',
    unitPrice: 1,
    totalPrice: 0,
    quantity: 0,
  },
  {
    name: 'Thé bio',
    category: 'Boisson',
    unitPrice: 1,
    totalPrice: 0,
    quantity: 0,
  },
  {
    name: 'Coca',
    category: 'Boisson',
    unitPrice: 3,
    totalPrice: 0,
    quantity: 0,
  },
  {
    name: 'Thé bio',
    category: 'Boisson',
    unitPrice: 1,
    totalPrice: 0,
    quantity: 0,
  },
  {
    name: 'Muffin',
    category: 'Dessert',
    unitPrice: 15,
    totalPrice: 0,
    quantity: 0,
  },
  {
    name: 'Fleurs Orange',
    category: 'Dessert',
    unitPrice: 50,
    totalPrice: 0,
    quantity: 0,
  },
  {
    name: 'Muffin',
    category: 'Dessert',
    unitPrice: 15,
    totalPrice: 0,
    quantity: 0,
  },
  {
    name: 'Fleurs Orange',
    category: 'Dessert',
    unitPrice: 50,
    totalPrice: 0,
    quantity: 0,
  },
  {
    name: 'Fleurs Orange',
    category: 'Dessert',
    unitPrice: 50,
    totalPrice: 0,
    quantity: 0,
  },
  {
    name: 'Fleurs Orange',
    category: 'Dessert',
    unitPrice: 50,
    totalPrice: 0,
    quantity: 0,
  },
  {
    name: 'Fleurs Orange',
    category: 'Dessert',
    unitPrice: 50,
    totalPrice: 0,
    quantity: 0,
  },
  {
    name: 'Fleurs Orange',
    category: 'Dessert',
    unitPrice: 50,
    totalPrice: 0,
    quantity: 0,
  },
  {
    name: 'Fleurs Orange',
    category: 'Dessert',
    unitPrice: 50,
    totalPrice: 0,
    quantity: 0,
  },
];

export default cart;
