const cart = [
  {
    id: 1,
    name: 'Thon',
    category: 'Sandwich',
    price: 1.5,
  },
  {
    id: 2,
    name: 'Thon',
    category: 'Sandwich',
    price: 1.5,
  },
  {
    id: 3,
    name: 'Thon',
    category: 'Sandwich',
    price: 1.5,
  },
  {
    id: 4,
    name: 'Thon',
    category: 'Sandwich',
    price: 1.5,
  },
  {
    id: 5,
    name: 'Thon',
    category: 'Sandwich',
    price: 1.5,
  },
  {
    id: 6,
    name: 'Thon',
    category: 'Sandwich',
    price: 1.5,
  },
  {
    id: 7,
    name: 'Thon',
    category: 'Sandwich',
    price: 1.5,
  },
  {
    id: 8,
    name: 'Blé',
    category: 'Sandwich',
    price: 2,
  },
  {
    id: 9,
    name: 'Thon',
    category: 'Sandwich',
    price: 1.5,
  },
  {
    id: 10,
    name: 'Thé bio',
    category: 'Boisson',
    price: 1,
  },
  {
    id: 11,
    name: 'Thé bio',
    category: 'Boisson',
    price: 1,
  },
  {
    id: 12,
    name: 'Thé bio',
    category: 'Boisson',
    price: 1,
  },
  {
    id: 13,
    name: 'Thé bio',
    category: 'Boisson',
    price: 1,
  },
  {
    id: 14,
    name: 'Thé bio',
    category: 'Boisson',
    price: 1,
  },
  {
    id: 15,
    name: 'Thé bio',
    category: 'Boisson',
    price: 1,
  },
  {
    id: 16,
    name: 'Thé bio',
    category: 'Boisson',
    price: 1,
  },
  {
    id: 17,
    name: 'Coca',
    category: 'Boisson',
    price: 3,
  },
  {
    id: 18,
    name: 'Thé bio',
    category: 'Boisson',
    price: 1,
  },
  {
    id: 19,
    name: 'Muffin',
    category: 'Dessert',
    price: 15,
  },
  {
    id: 20,
    name: 'Fleurs Orange',
    category: 'Dessert',
    price: 50,
  },
  {
    id: 21,
    name: 'Muffin',
    category: 'Dessert',
    unitPrice: 15,
  },
  {
    id: 22,
    name: 'Fleurs Orange',
    category: 'Dessert',
    unitPrice: 50,
  },
  {
    id: 23,
    name: 'Fleurs Orange',
    category: 'Dessert',
    unitPrice: 50,
  },
  {
    id: 24,
    name: 'Fleurs Orange',
    category: 'Dessert',
    unitPrice: 50,
  },
  {
    id: 25,
    name: 'Fleurs Orange',
    category: 'Dessert',
    unitPrice: 50,
  },
  {
    id: 26,
    name: 'Fleurs Orange',
    category: 'Dessert',
    unitPrice: 50,
  },
  {
    id: 27,
    name: 'Fleurs Orange',
    category: 'Dessert',
    unitPrice: 50,
  },
];

export default cart;
